/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Agency Client Portal API
 * OpenAPI spec version: 0.1.0
 */

export interface Activity {
  id: string;
  action: string;
  actor: string;
  createdAt: Date;
  type: string;
}
