/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Agency Client Portal API
 * OpenAPI spec version: 0.1.0
 */
export interface Agency {
    id: string;
    name: string;
    initials: string;
}
//# sourceMappingURL=agency.d.ts.map