/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Agency Client Portal API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface Error {
  error: string;
}

export interface Agency {
  id: string;
  name: string;
  initials: string;
}

export interface Client {
  id: string;
  name: string;
  email: string;
  company: string;
  initials: string;
  projectCount: number;
}

export interface Project {
  id: string;
  name: string;
  clientName: string;
  clientId: string;
  status: string;
  health: string;
  /**
     * @minimum 0
     * @maximum 100
     */
  progress: number;
  dueDate: string;
  budget: number;
  paid: number;
  milestoneCount: number;
  taskCount: number;
  /** @nullable */
  description?: string | null;
}

export interface Milestone {
  id: string;
  projectId: string;
  name: string;
  status: string;
  progress: number;
  dueDate: string;
  description: string;
}

export interface Task {
  id: string;
  projectId: string;
  title: string;
  owner: string;
  dueDate: string;
  priority: string;
  status: string;
}

export interface Deliverable {
  id: string;
  projectId: string;
  title: string;
  type: string;
  updatedAt: string;
  shareCount: number;
  url: string;
}

export interface Invoice {
  id: string;
  projectId: string;
  number: string;
  amount: number;
  status: string;
  dueDate: string;
  issuedDate: string;
}

export interface Activity {
  id: string;
  action: string;
  actor: string;
  createdAt: string;
  type: string;
}

export type ProjectDetail = Project & {
  milestones: Milestone[];
  tasks: Task[];
  deliverables: Deliverable[];
  invoices: Invoice[];
  activity: Activity[];
};

export interface ProjectInput {
  /** @minLength 1 */
  name: string;
  clientId: string;
  dueDate: string;
  /** @minimum 0 */
  budget: number;
  description?: string;
}

export interface ProjectUpdate {
  /** @minLength 1 */
  name?: string;
  status?: string;
  health?: string;
  /**
     * @minimum 0
     * @maximum 100
     */
  progress?: number;
  dueDate?: string;
  /** @minimum 0 */
  budget?: number;
  description?: string;
}

export interface ProjectList {
  items: Project[];
  total: number;
  page: number;
  pageSize: number;
}

export interface MilestoneInput {
  projectId: string;
  name: string;
  dueDate: string;
  description?: string;
}

export interface MilestoneUpdate {
  name?: string;
  status?: string;
  progress?: number;
  dueDate?: string;
  description?: string;
}

export interface TaskList {
  items: Task[];
  total: number;
  page: number;
  pageSize: number;
}

export interface TaskInput {
  projectId: string;
  title: string;
  owner?: string;
  dueDate: string;
  priority: string;
}

export interface TaskUpdate {
  title?: string;
  owner?: string;
  dueDate?: string;
  priority?: string;
  status?: string;
}

export interface InvoiceInput {
  projectId: string;
  /** @minimum 0 */
  amount: number;
  dueDate: string;
}

export interface Notification {
  id: string;
  title: string;
  description: string;
  type: string;
  createdAt: string;
  read: boolean;
}

export type DashboardStats = {
  activeProjects: number;
  dueThisWeek: number;
  outstanding: number;
  unreadNotifications: number;
};

export interface Dashboard {
  agency: Agency;
  stats: DashboardStats;
  projects: Project[];
  notifications: Notification[];
  activity: Activity[];
}

/**
 * Resource not found
 */
export type NotFoundResponse = Error;

export type ProjectIdOptionalParameter = string;

export type SearchParameter = string;

export type StatusParameter = string;

export type TaskStatusParameter = string;

export type PageParameter = number;

export type PageSizeParameter = number;

export type ListProjectsParams = {
search?: SearchParameter;
status?: StatusParameter;
/**
 * @minimum 1
 */
page?: PageParameter;
/**
 * @minimum 1
 * @maximum 100
 */
pageSize?: PageSizeParameter;
};

export type ListTasksParams = {
projectId?: ProjectIdOptionalParameter;
status?: TaskStatusParameter;
/**
 * @minimum 1
 */
page?: PageParameter;
/**
 * @minimum 1
 * @maximum 100
 */
pageSize?: PageSizeParameter;
};

export type ListMilestonesParams = {
projectId?: ProjectIdOptionalParameter;
};

export type ListDeliverablesParams = {
projectId?: ProjectIdOptionalParameter;
};

export type ListInvoicesParams = {
projectId?: ProjectIdOptionalParameter;
};

export type ListActivityParams = {
projectId?: ProjectIdOptionalParameter;
};

