/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Agency Client Portal API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * @summary Get agency dashboard summary
 */
export const getDashboardResponseProjectsItemProgressMin = 0;
export const getDashboardResponseProjectsItemProgressMax = 100;



export const GetDashboardResponse = zod.object({
  "agency": zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "initials": zod.string()
}),
  "stats": zod.object({
  "activeProjects": zod.number().int(),
  "dueThisWeek": zod.number().int(),
  "outstanding": zod.number(),
  "unreadNotifications": zod.number().int()
}),
  "projects": zod.array(zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "clientName": zod.string(),
  "clientId": zod.string(),
  "status": zod.string(),
  "health": zod.string(),
  "progress": zod.number().int().min(getDashboardResponseProjectsItemProgressMin).max(getDashboardResponseProjectsItemProgressMax),
  "dueDate": zod.coerce.date(),
  "budget": zod.number(),
  "paid": zod.number(),
  "milestoneCount": zod.number().int(),
  "taskCount": zod.number().int(),
  "description": zod.string().nullish()
})),
  "notifications": zod.array(zod.object({
  "id": zod.string(),
  "title": zod.string(),
  "description": zod.string(),
  "type": zod.string(),
  "createdAt": zod.coerce.date(),
  "read": zod.boolean()
})),
  "activity": zod.array(zod.object({
  "id": zod.string(),
  "action": zod.string(),
  "actor": zod.string(),
  "createdAt": zod.coerce.date(),
  "type": zod.string()
}))
})


/**
 * @summary List projects
 */
export const listProjectsQueryPageDefault = 1;

export const listProjectsQueryPageSizeDefault = 20;
export const listProjectsQueryPageSizeMax = 100;



export const ListProjectsQueryParams = zod.object({
  "search": zod.coerce.string().optional(),
  "status": zod.coerce.string().optional(),
  "page": zod.coerce.number().int().min(1).default(listProjectsQueryPageDefault),
  "pageSize": zod.coerce.number().int().min(1).max(listProjectsQueryPageSizeMax).default(listProjectsQueryPageSizeDefault)
})

export const listProjectsResponseItemsItemProgressMin = 0;
export const listProjectsResponseItemsItemProgressMax = 100;



export const ListProjectsResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "clientName": zod.string(),
  "clientId": zod.string(),
  "status": zod.string(),
  "health": zod.string(),
  "progress": zod.number().int().min(listProjectsResponseItemsItemProgressMin).max(listProjectsResponseItemsItemProgressMax),
  "dueDate": zod.coerce.date(),
  "budget": zod.number(),
  "paid": zod.number(),
  "milestoneCount": zod.number().int(),
  "taskCount": zod.number().int(),
  "description": zod.string().nullish()
})),
  "total": zod.number().int(),
  "page": zod.number().int(),
  "pageSize": zod.number().int()
})


/**
 * @summary Create a project
 */

export const createProjectBodyBudgetMin = 0;



export const CreateProjectBody = zod.object({
  "name": zod.string().min(1),
  "clientId": zod.string(),
  "dueDate": zod.coerce.date(),
  "budget": zod.number().min(createProjectBodyBudgetMin),
  "description": zod.string().optional()
})

export const createProjectResponseProgressMin = 0;
export const createProjectResponseProgressMax = 100;



export const CreateProjectResponse = zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "clientName": zod.string(),
  "clientId": zod.string(),
  "status": zod.string(),
  "health": zod.string(),
  "progress": zod.number().int().min(createProjectResponseProgressMin).max(createProjectResponseProgressMax),
  "dueDate": zod.coerce.date(),
  "budget": zod.number(),
  "paid": zod.number(),
  "milestoneCount": zod.number().int(),
  "taskCount": zod.number().int(),
  "description": zod.string().nullish()
})


/**
 * @summary Get project detail
 */
export const GetProjectParams = zod.object({
  "projectId": zod.coerce.string()
})

export const getProjectResponseOneProgressMin = 0;
export const getProjectResponseOneProgressMax = 100;



export const GetProjectResponse = zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "clientName": zod.string(),
  "clientId": zod.string(),
  "status": zod.string(),
  "health": zod.string(),
  "progress": zod.number().int().min(getProjectResponseOneProgressMin).max(getProjectResponseOneProgressMax),
  "dueDate": zod.coerce.date(),
  "budget": zod.number(),
  "paid": zod.number(),
  "milestoneCount": zod.number().int(),
  "taskCount": zod.number().int(),
  "description": zod.string().nullish()
}).and(zod.object({
  "milestones": zod.array(zod.object({
  "id": zod.string(),
  "projectId": zod.string(),
  "name": zod.string(),
  "status": zod.string(),
  "progress": zod.number().int(),
  "dueDate": zod.coerce.date(),
  "description": zod.string()
})),
  "tasks": zod.array(zod.object({
  "id": zod.string(),
  "projectId": zod.string(),
  "title": zod.string(),
  "owner": zod.string(),
  "dueDate": zod.coerce.date(),
  "priority": zod.string(),
  "status": zod.string()
})),
  "deliverables": zod.array(zod.object({
  "id": zod.string(),
  "projectId": zod.string(),
  "title": zod.string(),
  "type": zod.string(),
  "updatedAt": zod.coerce.date(),
  "shareCount": zod.number().int(),
  "url": zod.string()
})),
  "invoices": zod.array(zod.object({
  "id": zod.string(),
  "projectId": zod.string(),
  "number": zod.string(),
  "amount": zod.number(),
  "status": zod.string(),
  "dueDate": zod.coerce.date(),
  "issuedDate": zod.coerce.date()
})),
  "activity": zod.array(zod.object({
  "id": zod.string(),
  "action": zod.string(),
  "actor": zod.string(),
  "createdAt": zod.coerce.date(),
  "type": zod.string()
}))
}))


/**
 * @summary Update a project
 */
export const UpdateProjectParams = zod.object({
  "projectId": zod.coerce.string()
})


export const updateProjectBodyProgressMin = 0;
export const updateProjectBodyProgressMax = 100;

export const updateProjectBodyBudgetMin = 0;



export const UpdateProjectBody = zod.object({
  "name": zod.string().min(1).optional(),
  "status": zod.string().optional(),
  "health": zod.string().optional(),
  "progress": zod.number().int().min(updateProjectBodyProgressMin).max(updateProjectBodyProgressMax).optional(),
  "dueDate": zod.coerce.date().optional(),
  "budget": zod.number().min(updateProjectBodyBudgetMin).optional(),
  "description": zod.string().optional()
})

export const updateProjectResponseProgressMin = 0;
export const updateProjectResponseProgressMax = 100;



export const UpdateProjectResponse = zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "clientName": zod.string(),
  "clientId": zod.string(),
  "status": zod.string(),
  "health": zod.string(),
  "progress": zod.number().int().min(updateProjectResponseProgressMin).max(updateProjectResponseProgressMax),
  "dueDate": zod.coerce.date(),
  "budget": zod.number(),
  "paid": zod.number(),
  "milestoneCount": zod.number().int(),
  "taskCount": zod.number().int(),
  "description": zod.string().nullish()
})


/**
 * @summary Soft delete a project
 */
export const DeleteProjectParams = zod.object({
  "projectId": zod.coerce.string()
})

export const DeleteProjectResponse = zod.void()


/**
 * @summary List agency clients
 */
export const ListClientsResponseItem = zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "email": zod.string().email(),
  "company": zod.string(),
  "initials": zod.string(),
  "projectCount": zod.number().int()
})
export const ListClientsResponse = zod.array(ListClientsResponseItem)


/**
 * @summary List tasks
 */
export const listTasksQueryPageDefault = 1;

export const listTasksQueryPageSizeDefault = 20;
export const listTasksQueryPageSizeMax = 100;



export const ListTasksQueryParams = zod.object({
  "projectId": zod.coerce.string().optional(),
  "status": zod.coerce.string().optional(),
  "page": zod.coerce.number().int().min(1).default(listTasksQueryPageDefault),
  "pageSize": zod.coerce.number().int().min(1).max(listTasksQueryPageSizeMax).default(listTasksQueryPageSizeDefault)
})

export const ListTasksResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.string(),
  "projectId": zod.string(),
  "title": zod.string(),
  "owner": zod.string(),
  "dueDate": zod.coerce.date(),
  "priority": zod.string(),
  "status": zod.string()
})),
  "total": zod.number().int(),
  "page": zod.number().int(),
  "pageSize": zod.number().int()
})


/**
 * @summary Create a task
 */
export const CreateTaskBody = zod.object({
  "projectId": zod.string(),
  "title": zod.string(),
  "owner": zod.string().optional(),
  "dueDate": zod.coerce.date(),
  "priority": zod.string()
})

export const CreateTaskResponse = zod.object({
  "id": zod.string(),
  "projectId": zod.string(),
  "title": zod.string(),
  "owner": zod.string(),
  "dueDate": zod.coerce.date(),
  "priority": zod.string(),
  "status": zod.string()
})


/**
 * @summary Update a task
 */
export const UpdateTaskParams = zod.object({
  "taskId": zod.coerce.string()
})

export const UpdateTaskBody = zod.object({
  "title": zod.string().optional(),
  "owner": zod.string().optional(),
  "dueDate": zod.coerce.date().optional(),
  "priority": zod.string().optional(),
  "status": zod.string().optional()
})

export const UpdateTaskResponse = zod.object({
  "id": zod.string(),
  "projectId": zod.string(),
  "title": zod.string(),
  "owner": zod.string(),
  "dueDate": zod.coerce.date(),
  "priority": zod.string(),
  "status": zod.string()
})


/**
 * @summary List milestones
 */
export const ListMilestonesQueryParams = zod.object({
  "projectId": zod.coerce.string().optional()
})

export const ListMilestonesResponseItem = zod.object({
  "id": zod.string(),
  "projectId": zod.string(),
  "name": zod.string(),
  "status": zod.string(),
  "progress": zod.number().int(),
  "dueDate": zod.coerce.date(),
  "description": zod.string()
})
export const ListMilestonesResponse = zod.array(ListMilestonesResponseItem)


/**
 * @summary Create a milestone
 */
export const CreateMilestoneBody = zod.object({
  "projectId": zod.string(),
  "name": zod.string(),
  "dueDate": zod.coerce.date(),
  "description": zod.string().optional()
})

export const CreateMilestoneResponse = zod.object({
  "id": zod.string(),
  "projectId": zod.string(),
  "name": zod.string(),
  "status": zod.string(),
  "progress": zod.number().int(),
  "dueDate": zod.coerce.date(),
  "description": zod.string()
})


/**
 * @summary Update a milestone
 */
export const UpdateMilestoneParams = zod.object({
  "milestoneId": zod.coerce.string()
})

export const UpdateMilestoneBody = zod.object({
  "name": zod.string().optional(),
  "status": zod.string().optional(),
  "progress": zod.number().int().optional(),
  "dueDate": zod.coerce.date().optional(),
  "description": zod.string().optional()
})

export const UpdateMilestoneResponse = zod.object({
  "id": zod.string(),
  "projectId": zod.string(),
  "name": zod.string(),
  "status": zod.string(),
  "progress": zod.number().int(),
  "dueDate": zod.coerce.date(),
  "description": zod.string()
})


/**
 * @summary List deliverables
 */
export const ListDeliverablesQueryParams = zod.object({
  "projectId": zod.coerce.string().optional()
})

export const ListDeliverablesResponseItem = zod.object({
  "id": zod.string(),
  "projectId": zod.string(),
  "title": zod.string(),
  "type": zod.string(),
  "updatedAt": zod.coerce.date(),
  "shareCount": zod.number().int(),
  "url": zod.string()
})
export const ListDeliverablesResponse = zod.array(ListDeliverablesResponseItem)


/**
 * @summary List invoices
 */
export const ListInvoicesQueryParams = zod.object({
  "projectId": zod.coerce.string().optional()
})

export const ListInvoicesResponseItem = zod.object({
  "id": zod.string(),
  "projectId": zod.string(),
  "number": zod.string(),
  "amount": zod.number(),
  "status": zod.string(),
  "dueDate": zod.coerce.date(),
  "issuedDate": zod.coerce.date()
})
export const ListInvoicesResponse = zod.array(ListInvoicesResponseItem)


/**
 * @summary Create an invoice
 */
export const createInvoiceBodyAmountMin = 0;



export const CreateInvoiceBody = zod.object({
  "projectId": zod.string(),
  "amount": zod.number().min(createInvoiceBodyAmountMin),
  "dueDate": zod.coerce.date()
})

export const CreateInvoiceResponse = zod.object({
  "id": zod.string(),
  "projectId": zod.string(),
  "number": zod.string(),
  "amount": zod.number(),
  "status": zod.string(),
  "dueDate": zod.coerce.date(),
  "issuedDate": zod.coerce.date()
})


/**
 * @summary Mark an invoice paid
 */
export const MarkInvoicePaidParams = zod.object({
  "invoiceId": zod.coerce.string()
})

export const MarkInvoicePaidResponse = zod.object({
  "id": zod.string(),
  "projectId": zod.string(),
  "number": zod.string(),
  "amount": zod.number(),
  "status": zod.string(),
  "dueDate": zod.coerce.date(),
  "issuedDate": zod.coerce.date()
})


/**
 * @summary List notifications
 */
export const ListNotificationsResponseItem = zod.object({
  "id": zod.string(),
  "title": zod.string(),
  "description": zod.string(),
  "type": zod.string(),
  "createdAt": zod.coerce.date(),
  "read": zod.boolean()
})
export const ListNotificationsResponse = zod.array(ListNotificationsResponseItem)


/**
 * @summary List recent activity
 */
export const ListActivityQueryParams = zod.object({
  "projectId": zod.coerce.string().optional()
})

export const ListActivityResponseItem = zod.object({
  "id": zod.string(),
  "action": zod.string(),
  "actor": zod.string(),
  "createdAt": zod.coerce.date(),
  "type": zod.string()
})
export const ListActivityResponse = zod.array(ListActivityResponseItem)


