/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Agency Client Portal API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';
/**
 * @summary Health check
 */
export declare const HealthCheckResponse: zod.ZodObject<{
    status: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
}, {
    status: string;
}>;
/**
 * @summary Get agency dashboard summary
 */
export declare const getDashboardResponseProjectsItemProgressMin = 0;
export declare const getDashboardResponseProjectsItemProgressMax = 100;
export declare const GetDashboardResponse: zod.ZodObject<{
    agency: zod.ZodObject<{
        id: zod.ZodString;
        name: zod.ZodString;
        initials: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        id: string;
        name: string;
        initials: string;
    }, {
        id: string;
        name: string;
        initials: string;
    }>;
    stats: zod.ZodObject<{
        activeProjects: zod.ZodNumber;
        dueThisWeek: zod.ZodNumber;
        outstanding: zod.ZodNumber;
        unreadNotifications: zod.ZodNumber;
    }, "strip", zod.ZodTypeAny, {
        activeProjects: number;
        dueThisWeek: number;
        outstanding: number;
        unreadNotifications: number;
    }, {
        activeProjects: number;
        dueThisWeek: number;
        outstanding: number;
        unreadNotifications: number;
    }>;
    projects: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodString;
        name: zod.ZodString;
        clientName: zod.ZodString;
        clientId: zod.ZodString;
        status: zod.ZodString;
        health: zod.ZodString;
        progress: zod.ZodNumber;
        dueDate: zod.ZodDate;
        budget: zod.ZodNumber;
        paid: zod.ZodNumber;
        milestoneCount: zod.ZodNumber;
        taskCount: zod.ZodNumber;
        description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    }, "strip", zod.ZodTypeAny, {
        status: string;
        id: string;
        name: string;
        clientName: string;
        clientId: string;
        health: string;
        progress: number;
        dueDate: Date;
        budget: number;
        paid: number;
        milestoneCount: number;
        taskCount: number;
        description?: string | null | undefined;
    }, {
        status: string;
        id: string;
        name: string;
        clientName: string;
        clientId: string;
        health: string;
        progress: number;
        dueDate: Date;
        budget: number;
        paid: number;
        milestoneCount: number;
        taskCount: number;
        description?: string | null | undefined;
    }>, "many">;
    notifications: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodString;
        title: zod.ZodString;
        description: zod.ZodString;
        type: zod.ZodString;
        createdAt: zod.ZodDate;
        read: zod.ZodBoolean;
    }, "strip", zod.ZodTypeAny, {
        type: string;
        id: string;
        description: string;
        title: string;
        createdAt: Date;
        read: boolean;
    }, {
        type: string;
        id: string;
        description: string;
        title: string;
        createdAt: Date;
        read: boolean;
    }>, "many">;
    activity: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodString;
        action: zod.ZodString;
        actor: zod.ZodString;
        createdAt: zod.ZodDate;
        type: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        type: string;
        id: string;
        createdAt: Date;
        action: string;
        actor: string;
    }, {
        type: string;
        id: string;
        createdAt: Date;
        action: string;
        actor: string;
    }>, "many">;
}, "strip", zod.ZodTypeAny, {
    agency: {
        id: string;
        name: string;
        initials: string;
    };
    stats: {
        activeProjects: number;
        dueThisWeek: number;
        outstanding: number;
        unreadNotifications: number;
    };
    projects: {
        status: string;
        id: string;
        name: string;
        clientName: string;
        clientId: string;
        health: string;
        progress: number;
        dueDate: Date;
        budget: number;
        paid: number;
        milestoneCount: number;
        taskCount: number;
        description?: string | null | undefined;
    }[];
    notifications: {
        type: string;
        id: string;
        description: string;
        title: string;
        createdAt: Date;
        read: boolean;
    }[];
    activity: {
        type: string;
        id: string;
        createdAt: Date;
        action: string;
        actor: string;
    }[];
}, {
    agency: {
        id: string;
        name: string;
        initials: string;
    };
    stats: {
        activeProjects: number;
        dueThisWeek: number;
        outstanding: number;
        unreadNotifications: number;
    };
    projects: {
        status: string;
        id: string;
        name: string;
        clientName: string;
        clientId: string;
        health: string;
        progress: number;
        dueDate: Date;
        budget: number;
        paid: number;
        milestoneCount: number;
        taskCount: number;
        description?: string | null | undefined;
    }[];
    notifications: {
        type: string;
        id: string;
        description: string;
        title: string;
        createdAt: Date;
        read: boolean;
    }[];
    activity: {
        type: string;
        id: string;
        createdAt: Date;
        action: string;
        actor: string;
    }[];
}>;
/**
 * @summary List projects
 */
export declare const listProjectsQueryPageDefault = 1;
export declare const listProjectsQueryPageSizeDefault = 20;
export declare const listProjectsQueryPageSizeMax = 100;
export declare const ListProjectsQueryParams: zod.ZodObject<{
    search: zod.ZodOptional<zod.ZodString>;
    status: zod.ZodOptional<zod.ZodString>;
    page: zod.ZodDefault<zod.ZodNumber>;
    pageSize: zod.ZodDefault<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    page: number;
    pageSize: number;
    status?: string | undefined;
    search?: string | undefined;
}, {
    status?: string | undefined;
    search?: string | undefined;
    page?: number | undefined;
    pageSize?: number | undefined;
}>;
export declare const listProjectsResponseItemsItemProgressMin = 0;
export declare const listProjectsResponseItemsItemProgressMax = 100;
export declare const ListProjectsResponse: zod.ZodObject<{
    items: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodString;
        name: zod.ZodString;
        clientName: zod.ZodString;
        clientId: zod.ZodString;
        status: zod.ZodString;
        health: zod.ZodString;
        progress: zod.ZodNumber;
        dueDate: zod.ZodDate;
        budget: zod.ZodNumber;
        paid: zod.ZodNumber;
        milestoneCount: zod.ZodNumber;
        taskCount: zod.ZodNumber;
        description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    }, "strip", zod.ZodTypeAny, {
        status: string;
        id: string;
        name: string;
        clientName: string;
        clientId: string;
        health: string;
        progress: number;
        dueDate: Date;
        budget: number;
        paid: number;
        milestoneCount: number;
        taskCount: number;
        description?: string | null | undefined;
    }, {
        status: string;
        id: string;
        name: string;
        clientName: string;
        clientId: string;
        health: string;
        progress: number;
        dueDate: Date;
        budget: number;
        paid: number;
        milestoneCount: number;
        taskCount: number;
        description?: string | null | undefined;
    }>, "many">;
    total: zod.ZodNumber;
    page: zod.ZodNumber;
    pageSize: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    page: number;
    pageSize: number;
    items: {
        status: string;
        id: string;
        name: string;
        clientName: string;
        clientId: string;
        health: string;
        progress: number;
        dueDate: Date;
        budget: number;
        paid: number;
        milestoneCount: number;
        taskCount: number;
        description?: string | null | undefined;
    }[];
    total: number;
}, {
    page: number;
    pageSize: number;
    items: {
        status: string;
        id: string;
        name: string;
        clientName: string;
        clientId: string;
        health: string;
        progress: number;
        dueDate: Date;
        budget: number;
        paid: number;
        milestoneCount: number;
        taskCount: number;
        description?: string | null | undefined;
    }[];
    total: number;
}>;
/**
 * @summary Create a project
 */
export declare const createProjectBodyBudgetMin = 0;
export declare const CreateProjectBody: zod.ZodObject<{
    name: zod.ZodString;
    clientId: zod.ZodString;
    dueDate: zod.ZodDate;
    budget: zod.ZodNumber;
    description: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    name: string;
    clientId: string;
    dueDate: Date;
    budget: number;
    description?: string | undefined;
}, {
    name: string;
    clientId: string;
    dueDate: Date;
    budget: number;
    description?: string | undefined;
}>;
export declare const createProjectResponseProgressMin = 0;
export declare const createProjectResponseProgressMax = 100;
export declare const CreateProjectResponse: zod.ZodObject<{
    id: zod.ZodString;
    name: zod.ZodString;
    clientName: zod.ZodString;
    clientId: zod.ZodString;
    status: zod.ZodString;
    health: zod.ZodString;
    progress: zod.ZodNumber;
    dueDate: zod.ZodDate;
    budget: zod.ZodNumber;
    paid: zod.ZodNumber;
    milestoneCount: zod.ZodNumber;
    taskCount: zod.ZodNumber;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: string;
    name: string;
    clientName: string;
    clientId: string;
    health: string;
    progress: number;
    dueDate: Date;
    budget: number;
    paid: number;
    milestoneCount: number;
    taskCount: number;
    description?: string | null | undefined;
}, {
    status: string;
    id: string;
    name: string;
    clientName: string;
    clientId: string;
    health: string;
    progress: number;
    dueDate: Date;
    budget: number;
    paid: number;
    milestoneCount: number;
    taskCount: number;
    description?: string | null | undefined;
}>;
/**
 * @summary Get project detail
 */
export declare const GetProjectParams: zod.ZodObject<{
    projectId: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    projectId: string;
}, {
    projectId: string;
}>;
export declare const getProjectResponseOneProgressMin = 0;
export declare const getProjectResponseOneProgressMax = 100;
export declare const GetProjectResponse: zod.ZodIntersection<zod.ZodObject<{
    id: zod.ZodString;
    name: zod.ZodString;
    clientName: zod.ZodString;
    clientId: zod.ZodString;
    status: zod.ZodString;
    health: zod.ZodString;
    progress: zod.ZodNumber;
    dueDate: zod.ZodDate;
    budget: zod.ZodNumber;
    paid: zod.ZodNumber;
    milestoneCount: zod.ZodNumber;
    taskCount: zod.ZodNumber;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: string;
    name: string;
    clientName: string;
    clientId: string;
    health: string;
    progress: number;
    dueDate: Date;
    budget: number;
    paid: number;
    milestoneCount: number;
    taskCount: number;
    description?: string | null | undefined;
}, {
    status: string;
    id: string;
    name: string;
    clientName: string;
    clientId: string;
    health: string;
    progress: number;
    dueDate: Date;
    budget: number;
    paid: number;
    milestoneCount: number;
    taskCount: number;
    description?: string | null | undefined;
}>, zod.ZodObject<{
    milestones: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodString;
        projectId: zod.ZodString;
        name: zod.ZodString;
        status: zod.ZodString;
        progress: zod.ZodNumber;
        dueDate: zod.ZodDate;
        description: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        status: string;
        id: string;
        name: string;
        progress: number;
        dueDate: Date;
        description: string;
        projectId: string;
    }, {
        status: string;
        id: string;
        name: string;
        progress: number;
        dueDate: Date;
        description: string;
        projectId: string;
    }>, "many">;
    tasks: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodString;
        projectId: zod.ZodString;
        title: zod.ZodString;
        owner: zod.ZodString;
        dueDate: zod.ZodDate;
        priority: zod.ZodString;
        status: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        status: string;
        id: string;
        dueDate: Date;
        title: string;
        projectId: string;
        owner: string;
        priority: string;
    }, {
        status: string;
        id: string;
        dueDate: Date;
        title: string;
        projectId: string;
        owner: string;
        priority: string;
    }>, "many">;
    deliverables: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodString;
        projectId: zod.ZodString;
        title: zod.ZodString;
        type: zod.ZodString;
        updatedAt: zod.ZodDate;
        shareCount: zod.ZodNumber;
        url: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        type: string;
        id: string;
        title: string;
        projectId: string;
        updatedAt: Date;
        shareCount: number;
        url: string;
    }, {
        type: string;
        id: string;
        title: string;
        projectId: string;
        updatedAt: Date;
        shareCount: number;
        url: string;
    }>, "many">;
    invoices: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodString;
        projectId: zod.ZodString;
        number: zod.ZodString;
        amount: zod.ZodNumber;
        status: zod.ZodString;
        dueDate: zod.ZodDate;
        issuedDate: zod.ZodDate;
    }, "strip", zod.ZodTypeAny, {
        number: string;
        status: string;
        id: string;
        dueDate: Date;
        projectId: string;
        amount: number;
        issuedDate: Date;
    }, {
        number: string;
        status: string;
        id: string;
        dueDate: Date;
        projectId: string;
        amount: number;
        issuedDate: Date;
    }>, "many">;
    activity: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodString;
        action: zod.ZodString;
        actor: zod.ZodString;
        createdAt: zod.ZodDate;
        type: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        type: string;
        id: string;
        createdAt: Date;
        action: string;
        actor: string;
    }, {
        type: string;
        id: string;
        createdAt: Date;
        action: string;
        actor: string;
    }>, "many">;
}, "strip", zod.ZodTypeAny, {
    activity: {
        type: string;
        id: string;
        createdAt: Date;
        action: string;
        actor: string;
    }[];
    milestones: {
        status: string;
        id: string;
        name: string;
        progress: number;
        dueDate: Date;
        description: string;
        projectId: string;
    }[];
    tasks: {
        status: string;
        id: string;
        dueDate: Date;
        title: string;
        projectId: string;
        owner: string;
        priority: string;
    }[];
    deliverables: {
        type: string;
        id: string;
        title: string;
        projectId: string;
        updatedAt: Date;
        shareCount: number;
        url: string;
    }[];
    invoices: {
        number: string;
        status: string;
        id: string;
        dueDate: Date;
        projectId: string;
        amount: number;
        issuedDate: Date;
    }[];
}, {
    activity: {
        type: string;
        id: string;
        createdAt: Date;
        action: string;
        actor: string;
    }[];
    milestones: {
        status: string;
        id: string;
        name: string;
        progress: number;
        dueDate: Date;
        description: string;
        projectId: string;
    }[];
    tasks: {
        status: string;
        id: string;
        dueDate: Date;
        title: string;
        projectId: string;
        owner: string;
        priority: string;
    }[];
    deliverables: {
        type: string;
        id: string;
        title: string;
        projectId: string;
        updatedAt: Date;
        shareCount: number;
        url: string;
    }[];
    invoices: {
        number: string;
        status: string;
        id: string;
        dueDate: Date;
        projectId: string;
        amount: number;
        issuedDate: Date;
    }[];
}>>;
/**
 * @summary Update a project
 */
export declare const UpdateProjectParams: zod.ZodObject<{
    projectId: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    projectId: string;
}, {
    projectId: string;
}>;
export declare const updateProjectBodyProgressMin = 0;
export declare const updateProjectBodyProgressMax = 100;
export declare const updateProjectBodyBudgetMin = 0;
export declare const UpdateProjectBody: zod.ZodObject<{
    name: zod.ZodOptional<zod.ZodString>;
    status: zod.ZodOptional<zod.ZodString>;
    health: zod.ZodOptional<zod.ZodString>;
    progress: zod.ZodOptional<zod.ZodNumber>;
    dueDate: zod.ZodOptional<zod.ZodDate>;
    budget: zod.ZodOptional<zod.ZodNumber>;
    description: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    status?: string | undefined;
    name?: string | undefined;
    health?: string | undefined;
    progress?: number | undefined;
    dueDate?: Date | undefined;
    budget?: number | undefined;
    description?: string | undefined;
}, {
    status?: string | undefined;
    name?: string | undefined;
    health?: string | undefined;
    progress?: number | undefined;
    dueDate?: Date | undefined;
    budget?: number | undefined;
    description?: string | undefined;
}>;
export declare const updateProjectResponseProgressMin = 0;
export declare const updateProjectResponseProgressMax = 100;
export declare const UpdateProjectResponse: zod.ZodObject<{
    id: zod.ZodString;
    name: zod.ZodString;
    clientName: zod.ZodString;
    clientId: zod.ZodString;
    status: zod.ZodString;
    health: zod.ZodString;
    progress: zod.ZodNumber;
    dueDate: zod.ZodDate;
    budget: zod.ZodNumber;
    paid: zod.ZodNumber;
    milestoneCount: zod.ZodNumber;
    taskCount: zod.ZodNumber;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: string;
    name: string;
    clientName: string;
    clientId: string;
    health: string;
    progress: number;
    dueDate: Date;
    budget: number;
    paid: number;
    milestoneCount: number;
    taskCount: number;
    description?: string | null | undefined;
}, {
    status: string;
    id: string;
    name: string;
    clientName: string;
    clientId: string;
    health: string;
    progress: number;
    dueDate: Date;
    budget: number;
    paid: number;
    milestoneCount: number;
    taskCount: number;
    description?: string | null | undefined;
}>;
/**
 * @summary Soft delete a project
 */
export declare const DeleteProjectParams: zod.ZodObject<{
    projectId: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    projectId: string;
}, {
    projectId: string;
}>;
export declare const DeleteProjectResponse: zod.ZodVoid;
/**
 * @summary List agency clients
 */
export declare const ListClientsResponseItem: zod.ZodObject<{
    id: zod.ZodString;
    name: zod.ZodString;
    email: zod.ZodString;
    company: zod.ZodString;
    initials: zod.ZodString;
    projectCount: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: string;
    name: string;
    initials: string;
    email: string;
    company: string;
    projectCount: number;
}, {
    id: string;
    name: string;
    initials: string;
    email: string;
    company: string;
    projectCount: number;
}>;
export declare const ListClientsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodString;
    name: zod.ZodString;
    email: zod.ZodString;
    company: zod.ZodString;
    initials: zod.ZodString;
    projectCount: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: string;
    name: string;
    initials: string;
    email: string;
    company: string;
    projectCount: number;
}, {
    id: string;
    name: string;
    initials: string;
    email: string;
    company: string;
    projectCount: number;
}>, "many">;
/**
 * @summary List tasks
 */
export declare const listTasksQueryPageDefault = 1;
export declare const listTasksQueryPageSizeDefault = 20;
export declare const listTasksQueryPageSizeMax = 100;
export declare const ListTasksQueryParams: zod.ZodObject<{
    projectId: zod.ZodOptional<zod.ZodString>;
    status: zod.ZodOptional<zod.ZodString>;
    page: zod.ZodDefault<zod.ZodNumber>;
    pageSize: zod.ZodDefault<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    page: number;
    pageSize: number;
    status?: string | undefined;
    projectId?: string | undefined;
}, {
    status?: string | undefined;
    page?: number | undefined;
    pageSize?: number | undefined;
    projectId?: string | undefined;
}>;
export declare const ListTasksResponse: zod.ZodObject<{
    items: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodString;
        projectId: zod.ZodString;
        title: zod.ZodString;
        owner: zod.ZodString;
        dueDate: zod.ZodDate;
        priority: zod.ZodString;
        status: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        status: string;
        id: string;
        dueDate: Date;
        title: string;
        projectId: string;
        owner: string;
        priority: string;
    }, {
        status: string;
        id: string;
        dueDate: Date;
        title: string;
        projectId: string;
        owner: string;
        priority: string;
    }>, "many">;
    total: zod.ZodNumber;
    page: zod.ZodNumber;
    pageSize: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    page: number;
    pageSize: number;
    items: {
        status: string;
        id: string;
        dueDate: Date;
        title: string;
        projectId: string;
        owner: string;
        priority: string;
    }[];
    total: number;
}, {
    page: number;
    pageSize: number;
    items: {
        status: string;
        id: string;
        dueDate: Date;
        title: string;
        projectId: string;
        owner: string;
        priority: string;
    }[];
    total: number;
}>;
/**
 * @summary Create a task
 */
export declare const CreateTaskBody: zod.ZodObject<{
    projectId: zod.ZodString;
    title: zod.ZodString;
    owner: zod.ZodOptional<zod.ZodString>;
    dueDate: zod.ZodDate;
    priority: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    dueDate: Date;
    title: string;
    projectId: string;
    priority: string;
    owner?: string | undefined;
}, {
    dueDate: Date;
    title: string;
    projectId: string;
    priority: string;
    owner?: string | undefined;
}>;
export declare const CreateTaskResponse: zod.ZodObject<{
    id: zod.ZodString;
    projectId: zod.ZodString;
    title: zod.ZodString;
    owner: zod.ZodString;
    dueDate: zod.ZodDate;
    priority: zod.ZodString;
    status: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: string;
    dueDate: Date;
    title: string;
    projectId: string;
    owner: string;
    priority: string;
}, {
    status: string;
    id: string;
    dueDate: Date;
    title: string;
    projectId: string;
    owner: string;
    priority: string;
}>;
/**
 * @summary Update a task
 */
export declare const UpdateTaskParams: zod.ZodObject<{
    taskId: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    taskId: string;
}, {
    taskId: string;
}>;
export declare const UpdateTaskBody: zod.ZodObject<{
    title: zod.ZodOptional<zod.ZodString>;
    owner: zod.ZodOptional<zod.ZodString>;
    dueDate: zod.ZodOptional<zod.ZodDate>;
    priority: zod.ZodOptional<zod.ZodString>;
    status: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    status?: string | undefined;
    dueDate?: Date | undefined;
    title?: string | undefined;
    owner?: string | undefined;
    priority?: string | undefined;
}, {
    status?: string | undefined;
    dueDate?: Date | undefined;
    title?: string | undefined;
    owner?: string | undefined;
    priority?: string | undefined;
}>;
export declare const UpdateTaskResponse: zod.ZodObject<{
    id: zod.ZodString;
    projectId: zod.ZodString;
    title: zod.ZodString;
    owner: zod.ZodString;
    dueDate: zod.ZodDate;
    priority: zod.ZodString;
    status: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: string;
    dueDate: Date;
    title: string;
    projectId: string;
    owner: string;
    priority: string;
}, {
    status: string;
    id: string;
    dueDate: Date;
    title: string;
    projectId: string;
    owner: string;
    priority: string;
}>;
/**
 * @summary List milestones
 */
export declare const ListMilestonesQueryParams: zod.ZodObject<{
    projectId: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    projectId?: string | undefined;
}, {
    projectId?: string | undefined;
}>;
export declare const ListMilestonesResponseItem: zod.ZodObject<{
    id: zod.ZodString;
    projectId: zod.ZodString;
    name: zod.ZodString;
    status: zod.ZodString;
    progress: zod.ZodNumber;
    dueDate: zod.ZodDate;
    description: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: string;
    name: string;
    progress: number;
    dueDate: Date;
    description: string;
    projectId: string;
}, {
    status: string;
    id: string;
    name: string;
    progress: number;
    dueDate: Date;
    description: string;
    projectId: string;
}>;
export declare const ListMilestonesResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodString;
    projectId: zod.ZodString;
    name: zod.ZodString;
    status: zod.ZodString;
    progress: zod.ZodNumber;
    dueDate: zod.ZodDate;
    description: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: string;
    name: string;
    progress: number;
    dueDate: Date;
    description: string;
    projectId: string;
}, {
    status: string;
    id: string;
    name: string;
    progress: number;
    dueDate: Date;
    description: string;
    projectId: string;
}>, "many">;
/**
 * @summary Create a milestone
 */
export declare const CreateMilestoneBody: zod.ZodObject<{
    projectId: zod.ZodString;
    name: zod.ZodString;
    dueDate: zod.ZodDate;
    description: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    name: string;
    dueDate: Date;
    projectId: string;
    description?: string | undefined;
}, {
    name: string;
    dueDate: Date;
    projectId: string;
    description?: string | undefined;
}>;
export declare const CreateMilestoneResponse: zod.ZodObject<{
    id: zod.ZodString;
    projectId: zod.ZodString;
    name: zod.ZodString;
    status: zod.ZodString;
    progress: zod.ZodNumber;
    dueDate: zod.ZodDate;
    description: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: string;
    name: string;
    progress: number;
    dueDate: Date;
    description: string;
    projectId: string;
}, {
    status: string;
    id: string;
    name: string;
    progress: number;
    dueDate: Date;
    description: string;
    projectId: string;
}>;
/**
 * @summary Update a milestone
 */
export declare const UpdateMilestoneParams: zod.ZodObject<{
    milestoneId: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    milestoneId: string;
}, {
    milestoneId: string;
}>;
export declare const UpdateMilestoneBody: zod.ZodObject<{
    name: zod.ZodOptional<zod.ZodString>;
    status: zod.ZodOptional<zod.ZodString>;
    progress: zod.ZodOptional<zod.ZodNumber>;
    dueDate: zod.ZodOptional<zod.ZodDate>;
    description: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    status?: string | undefined;
    name?: string | undefined;
    progress?: number | undefined;
    dueDate?: Date | undefined;
    description?: string | undefined;
}, {
    status?: string | undefined;
    name?: string | undefined;
    progress?: number | undefined;
    dueDate?: Date | undefined;
    description?: string | undefined;
}>;
export declare const UpdateMilestoneResponse: zod.ZodObject<{
    id: zod.ZodString;
    projectId: zod.ZodString;
    name: zod.ZodString;
    status: zod.ZodString;
    progress: zod.ZodNumber;
    dueDate: zod.ZodDate;
    description: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
    id: string;
    name: string;
    progress: number;
    dueDate: Date;
    description: string;
    projectId: string;
}, {
    status: string;
    id: string;
    name: string;
    progress: number;
    dueDate: Date;
    description: string;
    projectId: string;
}>;
/**
 * @summary List deliverables
 */
export declare const ListDeliverablesQueryParams: zod.ZodObject<{
    projectId: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    projectId?: string | undefined;
}, {
    projectId?: string | undefined;
}>;
export declare const ListDeliverablesResponseItem: zod.ZodObject<{
    id: zod.ZodString;
    projectId: zod.ZodString;
    title: zod.ZodString;
    type: zod.ZodString;
    updatedAt: zod.ZodDate;
    shareCount: zod.ZodNumber;
    url: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    type: string;
    id: string;
    title: string;
    projectId: string;
    updatedAt: Date;
    shareCount: number;
    url: string;
}, {
    type: string;
    id: string;
    title: string;
    projectId: string;
    updatedAt: Date;
    shareCount: number;
    url: string;
}>;
export declare const ListDeliverablesResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodString;
    projectId: zod.ZodString;
    title: zod.ZodString;
    type: zod.ZodString;
    updatedAt: zod.ZodDate;
    shareCount: zod.ZodNumber;
    url: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    type: string;
    id: string;
    title: string;
    projectId: string;
    updatedAt: Date;
    shareCount: number;
    url: string;
}, {
    type: string;
    id: string;
    title: string;
    projectId: string;
    updatedAt: Date;
    shareCount: number;
    url: string;
}>, "many">;
/**
 * @summary List invoices
 */
export declare const ListInvoicesQueryParams: zod.ZodObject<{
    projectId: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    projectId?: string | undefined;
}, {
    projectId?: string | undefined;
}>;
export declare const ListInvoicesResponseItem: zod.ZodObject<{
    id: zod.ZodString;
    projectId: zod.ZodString;
    number: zod.ZodString;
    amount: zod.ZodNumber;
    status: zod.ZodString;
    dueDate: zod.ZodDate;
    issuedDate: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    number: string;
    status: string;
    id: string;
    dueDate: Date;
    projectId: string;
    amount: number;
    issuedDate: Date;
}, {
    number: string;
    status: string;
    id: string;
    dueDate: Date;
    projectId: string;
    amount: number;
    issuedDate: Date;
}>;
export declare const ListInvoicesResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodString;
    projectId: zod.ZodString;
    number: zod.ZodString;
    amount: zod.ZodNumber;
    status: zod.ZodString;
    dueDate: zod.ZodDate;
    issuedDate: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    number: string;
    status: string;
    id: string;
    dueDate: Date;
    projectId: string;
    amount: number;
    issuedDate: Date;
}, {
    number: string;
    status: string;
    id: string;
    dueDate: Date;
    projectId: string;
    amount: number;
    issuedDate: Date;
}>, "many">;
/**
 * @summary Create an invoice
 */
export declare const createInvoiceBodyAmountMin = 0;
export declare const CreateInvoiceBody: zod.ZodObject<{
    projectId: zod.ZodString;
    amount: zod.ZodNumber;
    dueDate: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    dueDate: Date;
    projectId: string;
    amount: number;
}, {
    dueDate: Date;
    projectId: string;
    amount: number;
}>;
export declare const CreateInvoiceResponse: zod.ZodObject<{
    id: zod.ZodString;
    projectId: zod.ZodString;
    number: zod.ZodString;
    amount: zod.ZodNumber;
    status: zod.ZodString;
    dueDate: zod.ZodDate;
    issuedDate: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    number: string;
    status: string;
    id: string;
    dueDate: Date;
    projectId: string;
    amount: number;
    issuedDate: Date;
}, {
    number: string;
    status: string;
    id: string;
    dueDate: Date;
    projectId: string;
    amount: number;
    issuedDate: Date;
}>;
/**
 * @summary Mark an invoice paid
 */
export declare const MarkInvoicePaidParams: zod.ZodObject<{
    invoiceId: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    invoiceId: string;
}, {
    invoiceId: string;
}>;
export declare const MarkInvoicePaidResponse: zod.ZodObject<{
    id: zod.ZodString;
    projectId: zod.ZodString;
    number: zod.ZodString;
    amount: zod.ZodNumber;
    status: zod.ZodString;
    dueDate: zod.ZodDate;
    issuedDate: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    number: string;
    status: string;
    id: string;
    dueDate: Date;
    projectId: string;
    amount: number;
    issuedDate: Date;
}, {
    number: string;
    status: string;
    id: string;
    dueDate: Date;
    projectId: string;
    amount: number;
    issuedDate: Date;
}>;
/**
 * @summary List notifications
 */
export declare const ListNotificationsResponseItem: zod.ZodObject<{
    id: zod.ZodString;
    title: zod.ZodString;
    description: zod.ZodString;
    type: zod.ZodString;
    createdAt: zod.ZodDate;
    read: zod.ZodBoolean;
}, "strip", zod.ZodTypeAny, {
    type: string;
    id: string;
    description: string;
    title: string;
    createdAt: Date;
    read: boolean;
}, {
    type: string;
    id: string;
    description: string;
    title: string;
    createdAt: Date;
    read: boolean;
}>;
export declare const ListNotificationsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodString;
    title: zod.ZodString;
    description: zod.ZodString;
    type: zod.ZodString;
    createdAt: zod.ZodDate;
    read: zod.ZodBoolean;
}, "strip", zod.ZodTypeAny, {
    type: string;
    id: string;
    description: string;
    title: string;
    createdAt: Date;
    read: boolean;
}, {
    type: string;
    id: string;
    description: string;
    title: string;
    createdAt: Date;
    read: boolean;
}>, "many">;
/**
 * @summary List recent activity
 */
export declare const ListActivityQueryParams: zod.ZodObject<{
    projectId: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    projectId?: string | undefined;
}, {
    projectId?: string | undefined;
}>;
export declare const ListActivityResponseItem: zod.ZodObject<{
    id: zod.ZodString;
    action: zod.ZodString;
    actor: zod.ZodString;
    createdAt: zod.ZodDate;
    type: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    type: string;
    id: string;
    createdAt: Date;
    action: string;
    actor: string;
}, {
    type: string;
    id: string;
    createdAt: Date;
    action: string;
    actor: string;
}>;
export declare const ListActivityResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodString;
    action: zod.ZodString;
    actor: zod.ZodString;
    createdAt: zod.ZodDate;
    type: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    type: string;
    id: string;
    createdAt: Date;
    action: string;
    actor: string;
}, {
    type: string;
    id: string;
    createdAt: Date;
    action: string;
    actor: string;
}>, "many">;
//# sourceMappingURL=api.d.ts.map