/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Agency Client Portal API
 * OpenAPI spec version: 0.1.0
 */
import type { Activity } from './activity';
import type { Agency } from './agency';
import type { DashboardStats } from './dashboardStats';
import type { Notification } from './notification';
import type { Project } from './project';

export interface Dashboard {
  agency: Agency;
  stats: DashboardStats;
  projects: Project[];
  notifications: Notification[];
  activity: Activity[];
}
