/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Agency Client Portal API
 * OpenAPI spec version: 0.1.0
 */
export interface Deliverable {
    id: string;
    projectId: string;
    title: string;
    type: string;
    updatedAt: Date;
    shareCount: number;
    url: string;
}
//# sourceMappingURL=deliverable.d.ts.map