/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Agency Client Portal API
 * OpenAPI spec version: 0.1.0
 */
export interface InvoiceInput {
    projectId: string;
    /** @minimum 0 */
    amount: number;
    dueDate: Date;
}
//# sourceMappingURL=invoiceInput.d.ts.map