/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Agency Client Portal API
 * OpenAPI spec version: 0.1.0
 */

export interface Invoice {
  id: string;
  projectId: string;
  number: string;
  amount: number;
  status: string;
  dueDate: Date;
  issuedDate: Date;
}
