/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Agency Client Portal API
 * OpenAPI spec version: 0.1.0
 */
import type { ProjectIdOptionalParameter } from './projectIdOptionalParameter';
export type ListActivityParams = {
    projectId?: ProjectIdOptionalParameter;
};
//# sourceMappingURL=listActivityParams.d.ts.map