/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Agency Client Portal API
 * OpenAPI spec version: 0.1.0
 */
import type { PageParameter } from './pageParameter';
import type { PageSizeParameter } from './pageSizeParameter';
import type { ProjectIdOptionalParameter } from './projectIdOptionalParameter';
import type { TaskStatusParameter } from './taskStatusParameter';

export type ListTasksParams = {
projectId?: ProjectIdOptionalParameter;
status?: TaskStatusParameter;
/**
 * @minimum 1
 */
page?: PageParameter;
/**
 * @minimum 1
 * @maximum 100
 */
pageSize?: PageSizeParameter;
};
