/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Agency Client Portal API
 * OpenAPI spec version: 0.1.0
 */
import type { ProjectIdOptionalParameter } from './projectIdOptionalParameter';

export type ListInvoicesParams = {
projectId?: ProjectIdOptionalParameter;
};
