/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Agency Client Portal API
 * OpenAPI spec version: 0.1.0
 */
export interface Milestone {
    id: string;
    projectId: string;
    name: string;
    status: string;
    progress: number;
    dueDate: Date;
    description: string;
}
//# sourceMappingURL=milestone.d.ts.map