/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Agency Client Portal API
 * OpenAPI spec version: 0.1.0
 */
export interface MilestoneUpdate {
    name?: string;
    status?: string;
    progress?: number;
    dueDate?: Date;
    description?: string;
}
//# sourceMappingURL=milestoneUpdate.d.ts.map