/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Agency Client Portal API
 * OpenAPI spec version: 0.1.0
 */
import type { Error } from './error';
/**
 * Resource not found
 */
export type NotFoundResponse = Error;
//# sourceMappingURL=notFoundResponse.d.ts.map