/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Agency Client Portal API
 * OpenAPI spec version: 0.1.0
 */

export interface Notification {
  id: string;
  title: string;
  description: string;
  type: string;
  createdAt: Date;
  read: boolean;
}
