/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Agency Client Portal API
 * OpenAPI spec version: 0.1.0
 */
import type { Project } from './project';
export interface ProjectList {
    items: Project[];
    total: number;
    page: number;
    pageSize: number;
}
//# sourceMappingURL=projectList.d.ts.map