/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Agency Client Portal API
 * OpenAPI spec version: 0.1.0
 */
export interface ProjectInput {
    /** @minLength 1 */
    name: string;
    clientId: string;
    dueDate: Date;
    /** @minimum 0 */
    budget: number;
    description?: string;
}
//# sourceMappingURL=projectInput.d.ts.map