/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Agency Client Portal API
 * OpenAPI spec version: 0.1.0
 */
export interface ProjectUpdate {
    /** @minLength 1 */
    name?: string;
    status?: string;
    health?: string;
    /**
       * @minimum 0
       * @maximum 100
       */
    progress?: number;
    dueDate?: Date;
    /** @minimum 0 */
    budget?: number;
    description?: string;
}
//# sourceMappingURL=projectUpdate.d.ts.map