/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Agency Client Portal API
 * OpenAPI spec version: 0.1.0
 */
export interface Project {
    id: string;
    name: string;
    clientName: string;
    clientId: string;
    status: string;
    health: string;
    /**
       * @minimum 0
       * @maximum 100
       */
    progress: number;
    dueDate: Date;
    budget: number;
    paid: number;
    milestoneCount: number;
    taskCount: number;
    /** @nullable */
    description?: string | null;
}
//# sourceMappingURL=project.d.ts.map