/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Agency Client Portal API
 * OpenAPI spec version: 0.1.0
 */
import type { Activity } from './activity';
import type { Deliverable } from './deliverable';
import type { Invoice } from './invoice';
import type { Milestone } from './milestone';
import type { Project } from './project';
import type { Task } from './task';
export type ProjectDetail = Project & {
    milestones: Milestone[];
    tasks: Task[];
    deliverables: Deliverable[];
    invoices: Invoice[];
    activity: Activity[];
};
//# sourceMappingURL=projectDetail.d.ts.map