/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Agency Client Portal API
 * OpenAPI spec version: 0.1.0
 */
export interface TaskUpdate {
    title?: string;
    owner?: string;
    dueDate?: Date;
    priority?: string;
    status?: string;
}
//# sourceMappingURL=taskUpdate.d.ts.map