/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Agency Client Portal API
 * OpenAPI spec version: 0.1.0
 */
import type { Task } from './task';

export interface TaskList {
  items: Task[];
  total: number;
  page: number;
  pageSize: number;
}
