/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * Agency Client Portal API
 * OpenAPI spec version: 0.1.0
 */
export interface TaskInput {
    projectId: string;
    title: string;
    owner?: string;
    dueDate: Date;
    priority: string;
}
//# sourceMappingURL=taskInput.d.ts.map